### ISSUE TITLE
Crash with latest version of Create

### ISSUE THREAD

**Issue by SlimF** [AeiouEnigma/Starlight#1]
If you create a contraption while using any 0.3.1 version the game crashes without a crashlog. Trying to then load the world shows a white screen for a while and crashes again.
If you downgrade to Create 0.3 it works without a problem. Sorry I can't help much with the description, if there's anything I can do to give more information, explain to me like how you'd explain it to a 6 years old and I will do it!

**Comment by AeiouEnigma** [comment]
This is unusual, because I have tested this fork exclusively with the latest 0.3.1c version of Create. Are you certain that you installed my version of Starlight?

Are you able to provide a latest.log?

**Comment by AeiouEnigma** [comment]
Additionally, could you please make sure to test using _only_ Starlight and Create, if you haven't already?

**Comment by SlimF** [comment]
I am using "starlight-forge-1.0.0-RC2-AeiouCreatePatch-2.jar" so I think I got the correct file. Here is latest.log and this time a crashlog was created so here it is too. This is with shaders enabled, but I tried without them too and it still crashed. Will try with only Starlight and Create and will report in a bit.

[latest.log](https://github.com/AeiouEnigma/Starlight/files/6526896/latest.log)
[crash-2021-05-22_20.50.43-client.txt](https://github.com/AeiouEnigma/Starlight/files/6526895/crash-2021-05-22_20.50.43-client.txt)

**Comment by SlimF** [comment]
Crashlog and latest.log with only Starlight and Create installed

[crash-2021-05-22_20.58.13-client.txt](https://github.com/AeiouEnigma/Starlight/files/6526900/crash-2021-05-22_20.58.13-client.txt)
[latest.log](https://github.com/AeiouEnigma/Starlight/files/6526901/latest.log)

**Comment by AeiouEnigma** [comment]
I'm unable to reproduce this crash. Can you describe exactly what kind of contraption you were trying to use?

**Comment by AeiouEnigma** [comment]
ope, hold on, I may have just reproduced it

**Comment by AeiouEnigma** [comment]
@SlimF please try this new release and confirm that it resolves the issue:

https://github.com/AeiouEnigma/Starlight/releases/download/1.0.0-RC2-Create-2/starlight-forge-1.0.0-RC2-AeiouCreatePatch_3.jar

**Comment by SlimF** [comment]
Will be able to test it out in 8-9 hours and report right after

**Comment by SlimF** [comment]
No crashes anymore, thank you so much!!
